export const qaIds = {
  productForm: {
    nameInput: "product-name-input",
    caloriesInput: "product-calories-input",
    proteinInput: "product-protein-input",
    fatInput: "product-fat-input",
    carbsInput: "product-carbs-input",
    saveButton: "product-save-button",
    deleteButton: "product-delete-button",
    categorySelect: "product-category-select",
    cookingSelect: "product-cooking-select",
    error: "product-form-error",
    deleteError: "product-delete-error",
  },
  productCard: {
    title: "product-card-title",
    calories: "product-card-calories",
    protein: "product-card-protein",
    fat: "product-card-fat",
    carbs: "product-card-carbs",
    category: "product-card-category",
    cooking: "product-card-cooking",
    composition: "product-card-composition",
    flags: "product-card-flags",
    createdAt: "product-card-created-at",
    updatedAt: "product-card-updated-at",
    id: "product-card-id",
  },
  dishForm: {
    nameInput: "dish-name-input",
    portionSizeInput: "dish-portion-size-input",
    caloriesInput: "dish-calories-input",
    proteinInput: "dish-protein-input",
    fatInput: "dish-fat-input",
    carbsInput: "dish-carbs-input",
    ingredientProductSelect: "dish-ingredient-product-select",
    ingredientGramsInput: "dish-ingredient-grams-input",
    categorySelect: "dish-category-select",
    addIngredientButton: "dish-add-ingredient-button",
    saveButton: "dish-save-button",
    deleteButton: "dish-delete-button",
    error: "dish-form-error",
  },
  dishCard: {
    title: "dish-card-title",
    calories: "dish-card-calories",
    protein: "dish-card-protein",
    fat: "dish-card-fat",
    carbs: "dish-card-carbs",
    portionSize: "dish-card-portion-size",
    category: "dish-card-category",
    flags: "dish-card-flags",
    ingredientsTable: "dish-card-ingredients-table",
    createdAt: "dish-card-created-at",
    updatedAt: "dish-card-updated-at",
    id: "dish-card-id",
  },
  productList: {
    createButton: "product-list-create-button",
    searchInput: "product-list-search-input",
    categorySelect: "product-list-category-select",
    cookingSelect: "product-list-cooking-select",
    veganCheckbox: "product-list-vegan-checkbox",
    glutenFreeCheckbox: "product-list-gluten-free-checkbox",
    sugarFreeCheckbox: "product-list-sugar-free-checkbox",
    sortSelect: "product-list-sort-select",
    orderSelect: "product-list-order-select",
    itemLink: "product-list-item-link",
    editLink: "product-list-edit-link",
  },
  dishList: {
    createButton: "dish-list-create-button",
    searchInput: "dish-list-search-input",
    categorySelect: "dish-list-category-select",
    veganCheckbox: "dish-list-vegan-checkbox",
    glutenFreeCheckbox: "dish-list-gluten-free-checkbox",
    sugarFreeCheckbox: "dish-list-sugar-free-checkbox",
    itemLink: "dish-list-item-link",
    editLink: "dish-list-edit-link",
  },
} as const;
