export const qaIds = {
  productForm: {
    nameInput: "product-name-input",
    caloriesInput: "product-calories-input",
    proteinInput: "product-protein-input",
    fatInput: "product-fat-input",
    carbsInput: "product-carbs-input",
    saveButton: "product-save-button",
    deleteButton: "product-delete-button",
    categorySelect: "product-category-select",
    cookingSelect: "product-cooking-select",
    error: "product-form-error",
    deleteError: "product-delete-error",
  },
  dishForm: {
    nameInput: "dish-name-input",
    portionSizeInput: "dish-portion-size-input",
    caloriesInput: "dish-calories-input",
    proteinInput: "dish-protein-input",
    fatInput: "dish-fat-input",
    carbsInput: "dish-carbs-input",
    ingredientProductSelect: "dish-ingredient-product-select",
    ingredientGramsInput: "dish-ingredient-grams-input",
    categorySelect: "dish-category-select",
    addIngredientButton: "dish-add-ingredient-button",
    saveButton: "dish-save-button",
    deleteButton: "dish-delete-button",
    error: "dish-form-error",
  },
  productList: {
    createButton: "product-list-create-button",
    searchInput: "product-list-search-input",
    categorySelect: "product-list-category-select",
    cookingSelect: "product-list-cooking-select",
    veganCheckbox: "product-list-vegan-checkbox",
    glutenFreeCheckbox: "product-list-gluten-free-checkbox",
    sugarFreeCheckbox: "product-list-sugar-free-checkbox",
    sortSelect: "product-list-sort-select",
    orderSelect: "product-list-order-select",
    itemLink: "product-list-item-link",
    editLink: "product-list-edit-link",
  },
  dishList: {
    createButton: "dish-list-create-button",
    searchInput: "dish-list-search-input",
    categorySelect: "dish-list-category-select",
    veganCheckbox: "dish-list-vegan-checkbox",
    glutenFreeCheckbox: "dish-list-gluten-free-checkbox",
    sugarFreeCheckbox: "dish-list-sugar-free-checkbox",
    itemLink: "dish-list-item-link",
    editLink: "dish-list-edit-link",
  },
} as const;
