import { qaIds } from '../../../src/lib/qaSelectors'

export const qaSelectors = {
  productForm: {
    root: `[data-qa-type="${qaIds.productForm.root}"]`,
    nameInput: `[data-qa-type="${qaIds.productForm.nameInput}"]`,
    caloriesInput: `[data-qa-type="${qaIds.productForm.caloriesInput}"]`,
    proteinInput: `[data-qa-type="${qaIds.productForm.proteinInput}"]`,
    fatInput: `[data-qa-type="${qaIds.productForm.fatInput}"]`,
    carbsInput: `[data-qa-type="${qaIds.productForm.carbsInput}"]`,
    saveButton: `[data-qa-type="${qaIds.productForm.saveButton}"]`,
    deleteButton: `[data-qa-type="${qaIds.productForm.deleteButton}"]`,
    categorySelect: `[data-qa-type="${qaIds.productForm.categorySelect}"]`,
    cookingSelect: `[data-qa-type="${qaIds.productForm.cookingSelect}"]`,
    error: `[data-qa-type="${qaIds.productForm.error}"]`,
    deleteError: `[data-qa-type="${qaIds.productForm.deleteError}"]`,
  },
  dishForm: {
    root: `[data-qa-type="${qaIds.dishForm.root}"]`,
    nameInput: `[data-qa-type="${qaIds.dishForm.nameInput}"]`,
    portionSizeInput: `[data-qa-type="${qaIds.dishForm.portionSizeInput}"]`,
    caloriesInput: `[data-qa-type="${qaIds.dishForm.caloriesInput}"]`,
    proteinInput: `[data-qa-type="${qaIds.dishForm.proteinInput}"]`,
    fatInput: `[data-qa-type="${qaIds.dishForm.fatInput}"]`,
    carbsInput: `[data-qa-type="${qaIds.dishForm.carbsInput}"]`,
    ingredientProductSelect: `[data-qa-type="${qaIds.dishForm.ingredientProductSelect}"]`,
    ingredientGramsInput: `[data-qa-type="${qaIds.dishForm.ingredientGramsInput}"]`,
    categorySelect: `[data-qa-type="${qaIds.dishForm.categorySelect}"]`,
    addIngredientButton: `[data-qa-type="${qaIds.dishForm.addIngredientButton}"]`,
    saveButton: `[data-qa-type="${qaIds.dishForm.saveButton}"]`,
    deleteButton: `[data-qa-type="${qaIds.dishForm.deleteButton}"]`,
    error: `[data-qa-type="${qaIds.dishForm.error}"]`,
  },
  productList: {
    root: `[data-qa-type="${qaIds.productList.root}"]`,
    createButton: `[data-qa-type="${qaIds.productList.createButton}"]`,
    searchInput: `[data-qa-type="${qaIds.productList.searchInput}"]`,
    categorySelect: `[data-qa-type="${qaIds.productList.categorySelect}"]`,
    cookingSelect: `[data-qa-type="${qaIds.productList.cookingSelect}"]`,
    veganCheckbox: `[data-qa-type="${qaIds.productList.veganCheckbox}"]`,
    sortSelect: `[data-qa-type="${qaIds.productList.sortSelect}"]`,
    orderSelect: `[data-qa-type="${qaIds.productList.orderSelect}"]`,
    itemLink: `[data-qa-type="${qaIds.productList.itemLink}"]`,
    editLink: `[data-qa-type="${qaIds.productList.editLink}"]`,
  },
  dishList: {
    root: `[data-qa-type="${qaIds.dishList.root}"]`,
    createButton: `[data-qa-type="${qaIds.dishList.createButton}"]`,
    searchInput: `[data-qa-type="${qaIds.dishList.searchInput}"]`,
    categorySelect: `[data-qa-type="${qaIds.dishList.categorySelect}"]`,
    veganCheckbox: `[data-qa-type="${qaIds.dishList.veganCheckbox}"]`,
    itemLink: `[data-qa-type="${qaIds.dishList.itemLink}"]`,
    editLink: `[data-qa-type="${qaIds.dishList.editLink}"]`,
  },
} as const;
